# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chinesegranny/CLionProjects/AutoFuzz

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chinesegranny/CLionProjects/AutoFuzz

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chinesegranny/CLionProjects/AutoFuzz/CMakeFiles /home/chinesegranny/CLionProjects/AutoFuzz//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chinesegranny/CLionProjects/AutoFuzz/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intrinsics_gen.dir/build.make CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named omp_gen

# Build rule for target.
omp_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 omp_gen
.PHONY : omp_gen

# fast build rule for target.
omp_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omp_gen.dir/build.make CMakeFiles/omp_gen.dir/build
.PHONY : omp_gen/fast

#=============================================================================
# Target rules for targets named acc_gen

# Build rule for target.
acc_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acc_gen
.PHONY : acc_gen

# fast build rule for target.
acc_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acc_gen.dir/build.make CMakeFiles/acc_gen.dir/build
.PHONY : acc_gen/fast

#=============================================================================
# Target rules for targets named AutoFuzz

# Build rule for target.
AutoFuzz: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AutoFuzz
.PHONY : AutoFuzz

# fast build rule for target.
AutoFuzz/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/build
.PHONY : AutoFuzz/fast

src/llvm/analysis/analysis.o: src/llvm/analysis/analysis.cc.o
.PHONY : src/llvm/analysis/analysis.o

# target to build an object file
src/llvm/analysis/analysis.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/llvm/analysis/analysis.cc.o
.PHONY : src/llvm/analysis/analysis.cc.o

src/llvm/analysis/analysis.i: src/llvm/analysis/analysis.cc.i
.PHONY : src/llvm/analysis/analysis.i

# target to preprocess a source file
src/llvm/analysis/analysis.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/llvm/analysis/analysis.cc.i
.PHONY : src/llvm/analysis/analysis.cc.i

src/llvm/analysis/analysis.s: src/llvm/analysis/analysis.cc.s
.PHONY : src/llvm/analysis/analysis.s

# target to generate assembly for a file
src/llvm/analysis/analysis.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/llvm/analysis/analysis.cc.s
.PHONY : src/llvm/analysis/analysis.cc.s

src/llvm/generator/fuzzer_generator.o: src/llvm/generator/fuzzer_generator.cc.o
.PHONY : src/llvm/generator/fuzzer_generator.o

# target to build an object file
src/llvm/generator/fuzzer_generator.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/llvm/generator/fuzzer_generator.cc.o
.PHONY : src/llvm/generator/fuzzer_generator.cc.o

src/llvm/generator/fuzzer_generator.i: src/llvm/generator/fuzzer_generator.cc.i
.PHONY : src/llvm/generator/fuzzer_generator.i

# target to preprocess a source file
src/llvm/generator/fuzzer_generator.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/llvm/generator/fuzzer_generator.cc.i
.PHONY : src/llvm/generator/fuzzer_generator.cc.i

src/llvm/generator/fuzzer_generator.s: src/llvm/generator/fuzzer_generator.cc.s
.PHONY : src/llvm/generator/fuzzer_generator.s

# target to generate assembly for a file
src/llvm/generator/fuzzer_generator.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/llvm/generator/fuzzer_generator.cc.s
.PHONY : src/llvm/generator/fuzzer_generator.cc.s

src/llvm/generator/name_corrector.o: src/llvm/generator/name_corrector.cc.o
.PHONY : src/llvm/generator/name_corrector.o

# target to build an object file
src/llvm/generator/name_corrector.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/llvm/generator/name_corrector.cc.o
.PHONY : src/llvm/generator/name_corrector.cc.o

src/llvm/generator/name_corrector.i: src/llvm/generator/name_corrector.cc.i
.PHONY : src/llvm/generator/name_corrector.i

# target to preprocess a source file
src/llvm/generator/name_corrector.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/llvm/generator/name_corrector.cc.i
.PHONY : src/llvm/generator/name_corrector.cc.i

src/llvm/generator/name_corrector.s: src/llvm/generator/name_corrector.cc.s
.PHONY : src/llvm/generator/name_corrector.s

# target to generate assembly for a file
src/llvm/generator/name_corrector.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/llvm/generator/name_corrector.cc.s
.PHONY : src/llvm/generator/name_corrector.cc.s

src/llvm/generator/sanitizer.o: src/llvm/generator/sanitizer.cc.o
.PHONY : src/llvm/generator/sanitizer.o

# target to build an object file
src/llvm/generator/sanitizer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/llvm/generator/sanitizer.cc.o
.PHONY : src/llvm/generator/sanitizer.cc.o

src/llvm/generator/sanitizer.i: src/llvm/generator/sanitizer.cc.i
.PHONY : src/llvm/generator/sanitizer.i

# target to preprocess a source file
src/llvm/generator/sanitizer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/llvm/generator/sanitizer.cc.i
.PHONY : src/llvm/generator/sanitizer.cc.i

src/llvm/generator/sanitizer.s: src/llvm/generator/sanitizer.cc.s
.PHONY : src/llvm/generator/sanitizer.s

# target to generate assembly for a file
src/llvm/generator/sanitizer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/llvm/generator/sanitizer.cc.s
.PHONY : src/llvm/generator/sanitizer.cc.s

src/llvm/pass_launcher.o: src/llvm/pass_launcher.cc.o
.PHONY : src/llvm/pass_launcher.o

# target to build an object file
src/llvm/pass_launcher.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/llvm/pass_launcher.cc.o
.PHONY : src/llvm/pass_launcher.cc.o

src/llvm/pass_launcher.i: src/llvm/pass_launcher.cc.i
.PHONY : src/llvm/pass_launcher.i

# target to preprocess a source file
src/llvm/pass_launcher.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/llvm/pass_launcher.cc.i
.PHONY : src/llvm/pass_launcher.cc.i

src/llvm/pass_launcher.s: src/llvm/pass_launcher.cc.s
.PHONY : src/llvm/pass_launcher.s

# target to generate assembly for a file
src/llvm/pass_launcher.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/llvm/pass_launcher.cc.s
.PHONY : src/llvm/pass_launcher.cc.s

src/main.o: src/main.cc.o
.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/module.o: src/module.cc.o
.PHONY : src/module.o

# target to build an object file
src/module.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/module.cc.o
.PHONY : src/module.cc.o

src/module.i: src/module.cc.i
.PHONY : src/module.i

# target to preprocess a source file
src/module.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/module.cc.i
.PHONY : src/module.cc.i

src/module.s: src/module.cc.s
.PHONY : src/module.s

# target to generate assembly for a file
src/module.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/module.cc.s
.PHONY : src/module.cc.s

src/system/compiler.o: src/system/compiler.cc.o
.PHONY : src/system/compiler.o

# target to build an object file
src/system/compiler.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/system/compiler.cc.o
.PHONY : src/system/compiler.cc.o

src/system/compiler.i: src/system/compiler.cc.i
.PHONY : src/system/compiler.i

# target to preprocess a source file
src/system/compiler.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/system/compiler.cc.i
.PHONY : src/system/compiler.cc.i

src/system/compiler.s: src/system/compiler.cc.s
.PHONY : src/system/compiler.s

# target to generate assembly for a file
src/system/compiler.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/system/compiler.cc.s
.PHONY : src/system/compiler.cc.s

src/system/file.o: src/system/file.cc.o
.PHONY : src/system/file.o

# target to build an object file
src/system/file.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/system/file.cc.o
.PHONY : src/system/file.cc.o

src/system/file.i: src/system/file.cc.i
.PHONY : src/system/file.i

# target to preprocess a source file
src/system/file.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/system/file.cc.i
.PHONY : src/system/file.cc.i

src/system/file.s: src/system/file.cc.s
.PHONY : src/system/file.s

# target to generate assembly for a file
src/system/file.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/system/file.cc.s
.PHONY : src/system/file.cc.s

src/system/source_wrapper.o: src/system/source_wrapper.cc.o
.PHONY : src/system/source_wrapper.o

# target to build an object file
src/system/source_wrapper.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/system/source_wrapper.cc.o
.PHONY : src/system/source_wrapper.cc.o

src/system/source_wrapper.i: src/system/source_wrapper.cc.i
.PHONY : src/system/source_wrapper.i

# target to preprocess a source file
src/system/source_wrapper.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/system/source_wrapper.cc.i
.PHONY : src/system/source_wrapper.cc.i

src/system/source_wrapper.s: src/system/source_wrapper.cc.s
.PHONY : src/system/source_wrapper.s

# target to generate assembly for a file
src/system/source_wrapper.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/system/source_wrapper.cc.s
.PHONY : src/system/source_wrapper.cc.s

src/system/virtual_mapper.o: src/system/virtual_mapper.cc.o
.PHONY : src/system/virtual_mapper.o

# target to build an object file
src/system/virtual_mapper.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/system/virtual_mapper.cc.o
.PHONY : src/system/virtual_mapper.cc.o

src/system/virtual_mapper.i: src/system/virtual_mapper.cc.i
.PHONY : src/system/virtual_mapper.i

# target to preprocess a source file
src/system/virtual_mapper.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/system/virtual_mapper.cc.i
.PHONY : src/system/virtual_mapper.cc.i

src/system/virtual_mapper.s: src/system/virtual_mapper.cc.s
.PHONY : src/system/virtual_mapper.s

# target to generate assembly for a file
src/system/virtual_mapper.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/system/virtual_mapper.cc.s
.PHONY : src/system/virtual_mapper.cc.s

src/utils.o: src/utils.cc.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/utils.cc.o
.PHONY : src/utils.cc.o

src/utils.i: src/utils.cc.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/utils.cc.i
.PHONY : src/utils.cc.i

src/utils.s: src/utils.cc.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AutoFuzz.dir/build.make CMakeFiles/AutoFuzz.dir/src/utils.cc.s
.PHONY : src/utils.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... acc_gen"
	@echo "... intrinsics_gen"
	@echo "... omp_gen"
	@echo "... AutoFuzz"
	@echo "... src/llvm/analysis/analysis.o"
	@echo "... src/llvm/analysis/analysis.i"
	@echo "... src/llvm/analysis/analysis.s"
	@echo "... src/llvm/generator/fuzzer_generator.o"
	@echo "... src/llvm/generator/fuzzer_generator.i"
	@echo "... src/llvm/generator/fuzzer_generator.s"
	@echo "... src/llvm/generator/name_corrector.o"
	@echo "... src/llvm/generator/name_corrector.i"
	@echo "... src/llvm/generator/name_corrector.s"
	@echo "... src/llvm/generator/sanitizer.o"
	@echo "... src/llvm/generator/sanitizer.i"
	@echo "... src/llvm/generator/sanitizer.s"
	@echo "... src/llvm/pass_launcher.o"
	@echo "... src/llvm/pass_launcher.i"
	@echo "... src/llvm/pass_launcher.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/module.o"
	@echo "... src/module.i"
	@echo "... src/module.s"
	@echo "... src/system/compiler.o"
	@echo "... src/system/compiler.i"
	@echo "... src/system/compiler.s"
	@echo "... src/system/file.o"
	@echo "... src/system/file.i"
	@echo "... src/system/file.s"
	@echo "... src/system/source_wrapper.o"
	@echo "... src/system/source_wrapper.i"
	@echo "... src/system/source_wrapper.s"
	@echo "... src/system/virtual_mapper.o"
	@echo "... src/system/virtual_mapper.i"
	@echo "... src/system/virtual_mapper.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

