#!/bin/bash

cd curl-7.81.0/ || tar xvfz curl-7.81.0.tar.gz && cd curl-7.81.0/
# Compile
export LLVM_COMPILER=clang
CC=wllvm ./configure --with-openssl
make
unset LLVM_COMPILER
cd ..
# Extract
extract-bc --manifest --bitcode curl-7.81.0/lib/.libs/libcurl.a
llvm-dis curl-7.81.0/lib/.libs/libcurl.a.bc -o libcurl.ll
mv curl-7.81.0/lib/.libs/libcurl.a.llvm.manifest MANIFEST.txt
