#!/bin/bash

FILENAME=curl-7.85.0

PROJECT=$HOME/CLionProjects/AutoFuzz/test/fuzzing/libcurl/"$FILENAME"
EXECUTABLE=$HOME/CLionProjects/AutoFuzz/test/fuzzing/libcurl/"$FILENAME"/lib/.libs/libcurl.so
MANIFEST=MANIFEST.txt

#
# Paths to scripts
#
compile=$HOME/CLionProjects/AutoFuzz/scripts/compilation/compile
link=$HOME/CLionProjects/AutoFuzz/scripts/compilation/link
interpret=$HOME/CLionProjects/AutoFuzz/scripts/compilation/interpret

#
# Do the business
#
# Compile to libcurl.so
$compile -A --args=--with-openssl "$PROJECT"
# Convert libcurl.so to libcurl.ll and generate MANIFEST.txt
$link "$EXECUTABLE"
# Find all source files from MANIFEST.txt
$interpret -M $MANIFEST "$PROJECT"

rm $MANIFEST