#!/bin/bash

export LLVM_COMPILER=clang
CXX=wllvm++ cmake .
make
unset LLVM_COMPILER
extract-bc --manifest fuzztrigger
llvm-dis fuzztrigger.bc -o fuzztrigger.ll
mv fuzztrigger.llvm.manifest MANIFEST.txt
