#!/bin/bash

#
# Targets to process
#
PROJECT=$HOME/CLionProjects/AutoFuzz/test/fuzzing/libcurl/curl-7.81.0
EXECUTABLE=$HOME/CLionProjects/AutoFuzz/test/fuzzing/libcurl/curl-7.81.0/lib/.libs/libcurl.so
MANIFEST=MANIFEST.txt

#
# Paths to scripts
#
compile=$HOME/CLionProjects/AutoFuzz/scripts/compilation/compile
link=$HOME/CLionProjects/AutoFuzz/scripts/compilation/link
interpret=$HOME/CLionProjects/AutoFuzz/scripts/compilation/interpret

# Compile to libcurl.so
$compile -A --args=--with-openssl $PROJECT
# Convert libcurl.so to libcurl.ll and generate MANIFEST.txt
$link $EXECUTABLE
# Find all source files from MANIFEST.txt
$interpret -M $MANIFEST $PROJECT

rm $MANIFEST